name: Deploy to Surge.sh

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # Accede al secreto de manera segura
        run: surge --project ./ --domain coherent-desk.surge.sh --token ${{ env.SURGE_TOKEN }}